kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 41491
nodes:
- role: control-plane
  extraMounts:
  - hostPath: configs/dev/files/kind-pregenerated-certs
    containerPath: /mnt/kind-pregenerated-certs
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration 
    certificatesDir: /mnt/kind-pregenerated-certs
  extraPortMappings:
  - containerPort: 80
    hostPort: 41080
    protocol: TCP
  - containerPort: 443
    hostPort: 41443
    protocol: TCP