kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 41491
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/localadmin/chuv/chorus/chorus-backend/configs/dev/files/kind-pregenerated-certs
    containerPath: /mnt/kind-pregenerated-certs
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration 
    certificatesDir: /mnt/kind-pregenerated-certs