swagger: "2.0"
info:
  title: chorus workspace service
  version: "1.0"
  contact:
    name: chorus workspace service
    url: https://github.com/CHORUS-TRE/chorus-backend
    email: dev@chorus-tre.ch
tags:
  - name: WorkspaceService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/rest/v1/workspaces:
    get:
      summary: List workspaces
      description: This endpoint returns a list of workspaces
      operationId: WorkspaceService_ListWorkspaces
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusListWorkspacesReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: pagination.offset
          description: Optionally offset the number of results
          in: query
          required: false
          type: integer
          format: int64
        - name: pagination.limit
          description: Optionally limit the number of results (between 1 and 500)
          in: query
          required: false
          type: integer
          format: int64
        - name: pagination.sort.order
          in: query
          required: false
          type: string
        - name: pagination.sort.type
          in: query
          required: false
          type: string
        - name: pagination.query
          description: Optionally filter the results
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          x-example:
            - user_id=9999
            - status=STATUS_CREATED,STATUS_CLOSED
        - name: filter.workspaceIdsIn
          in: query
          required: false
          type: array
          items:
            type: string
            format: uint64
          collectionFormat: multi
      tags:
        - WorkspaceService
    post:
      summary: Create a workspace
      description: This endpoint creates a workspace
      operationId: WorkspaceService_CreateWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusCreateWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusWorkspace'
      tags:
        - WorkspaceService
    put:
      summary: Update a workspace
      description: This endpoint updates a workspace
      operationId: WorkspaceService_UpdateWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusUpdateWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusWorkspace'
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{id}:
    get:
      summary: Get a workspace
      description: This endpoint returns a workspace
      operationId: WorkspaceService_GetWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusGetWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - WorkspaceService
    delete:
      summary: Delete a workspace
      description: This endpoint deletes a workspace
      operationId: WorkspaceService_DeleteWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusDeleteWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{id}/user/{userId}:
    delete:
      summary: Remove a user from a workspace
      description: This endpoint removes a user from a workspace
      operationId: WorkspaceService_RemoveUserFromWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusRemoveUserFromWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
        - name: userId
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{id}/user/{userId}/role:
    post:
      summary: Manage a user's role in a workspace
      description: This endpoint manages a user's role in a workspace
      operationId: WorkspaceService_ManageUserRoleInWorkspace
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusManageUserRoleInWorkspaceReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
        - name: userId
          in: path
          required: true
          type: string
          format: uint64
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/WorkspaceServiceManageUserRoleInWorkspaceBody'
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{workspaceId}/files:
    post:
      summary: Create a file in a workspace
      description: This endpoint creates a file in a workspace at the specified path
      operationId: WorkspaceService_CreateWorkspaceFile
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusCreateWorkspaceFileReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: workspaceId
          in: path
          required: true
          type: string
          format: uint64
        - name: file
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusWorkspaceFile'
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{workspaceId}/files/{oldPath}:
    put:
      summary: Update a file in a workspace
      description: This endpoint updates (rename or moves) a file in a workspace at the specified path
      operationId: WorkspaceService_UpdateWorkspaceFile
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusUpdateWorkspaceFileReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: workspaceId
          in: path
          required: true
          type: string
          format: uint64
        - name: oldPath
          description: For renaming or moving files
          in: path
          required: true
          type: string
          pattern: .+
        - name: file
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusWorkspaceFile'
      tags:
        - WorkspaceService
  /api/rest/v1/workspaces/{workspaceId}/files/{path}:
    get:
      summary: List files in a workspace
      description: This endpoint lists all files at given path within a workspace
      operationId: WorkspaceService_GetWorkspaceFile
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusGetWorkspaceFileReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: workspaceId
          in: path
          required: true
          type: string
          format: uint64
        - name: path
          in: path
          required: true
          type: string
          pattern: .+
      tags:
        - WorkspaceService
    delete:
      summary: Delete a file in a workspace
      description: This endpoint deletes a file in a workspace at the specified path
      operationId: WorkspaceService_DeleteWorkspaceFile
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/chorusDeleteWorkspaceFileReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: workspaceId
          in: path
          required: true
          type: string
          format: uint64
        - name: path
          in: path
          required: true
          type: string
          pattern: .+
      tags:
        - WorkspaceService
definitions:
  WorkspaceServiceManageUserRoleInWorkspaceBody:
    type: object
    properties:
      role:
        $ref: '#/definitions/chorusRole'
  chorusCreateWorkspaceFileReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusCreateWorkspaceFileResult'
  chorusCreateWorkspaceFileResult:
    type: object
    properties:
      file:
        $ref: '#/definitions/chorusWorkspaceFile'
  chorusCreateWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusCreateWorkspaceResult'
  chorusCreateWorkspaceResult:
    type: object
    properties:
      workspace:
        $ref: '#/definitions/chorusWorkspace'
  chorusDeleteWorkspaceFileReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusDeleteWorkspaceFileResult'
  chorusDeleteWorkspaceFileResult:
    type: object
  chorusDeleteWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusDeleteWorkspaceResult'
  chorusDeleteWorkspaceResult:
    type: object
  chorusGetWorkspaceFileReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusGetWorkspaceFileResult'
  chorusGetWorkspaceFileResult:
    type: object
    properties:
      file:
        $ref: '#/definitions/chorusWorkspaceFile'
  chorusGetWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusGetWorkspaceResult'
  chorusGetWorkspaceResult:
    type: object
    properties:
      workspace:
        $ref: '#/definitions/chorusWorkspace'
  chorusListWorkspacesReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusListWorkspacesResult'
      pagination:
        $ref: '#/definitions/chorusPaginationResult'
  chorusListWorkspacesResult:
    type: object
    properties:
      workspaces:
        type: array
        items:
          type: object
          $ref: '#/definitions/chorusWorkspace'
  chorusManageUserRoleInWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusManageUserRoleInWorkspaceResult'
  chorusManageUserRoleInWorkspaceResult:
    type: object
    properties:
      workspace:
        $ref: '#/definitions/chorusWorkspace'
  chorusPaginationQuery:
    type: object
    properties:
      offset:
        type: integer
        format: int64
        description: Optionally offset the number of results
      limit:
        type: integer
        format: int64
        description: Optionally limit the number of results (between 1 and 500)
      sort:
        $ref: '#/definitions/chorusSort'
        description: Optionally sort the results
      query:
        type: array
        items:
          type: string
        description: Optionally filter the results
        x-example:
          - user_id=9999
          - status=STATUS_CREATED,STATUS_CLOSED
  chorusPaginationResult:
    type: object
    properties:
      total:
        type: integer
        format: int64
        description: Total number of results
      offset:
        type: integer
        format: int64
        description: Offset used for pagination
      limit:
        type: integer
        format: int64
        description: Limit used for pagination
      sort:
        $ref: '#/definitions/chorusSort'
        description: Sort order used for pagination
  chorusRemoveUserFromWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusRemoveUserFromWorkspaceResult'
  chorusRemoveUserFromWorkspaceResult:
    type: object
    properties:
      workspace:
        $ref: '#/definitions/chorusWorkspace'
  chorusRole:
    type: object
    properties:
      name:
        type: string
      context:
        type: object
        additionalProperties:
          type: string
  chorusSort:
    type: object
    properties:
      order:
        type: string
      type:
        type: string
  chorusUpdateWorkspaceFileReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusUpdateWorkspaceFileResult'
  chorusUpdateWorkspaceFileResult:
    type: object
    properties:
      file:
        $ref: '#/definitions/chorusWorkspaceFile'
  chorusUpdateWorkspaceReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/chorusUpdateWorkspaceResult'
  chorusUpdateWorkspaceResult:
    type: object
    properties:
      workspace:
        $ref: '#/definitions/chorusWorkspace'
  chorusWorkspace:
    type: object
    properties:
      id:
        type: string
        format: uint64
      tenantId:
        type: string
        format: uint64
      userId:
        type: string
        format: uint64
      name:
        type: string
      shortName:
        type: string
      description:
        type: string
      status:
        type: string
      isMain:
        type: boolean
      appInsanceIds:
        type: array
        items:
          type: string
          format: uint64
      appInstances:
        type: array
        items:
          type: string
          format: uint64
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  chorusWorkspaceFile:
    type: object
    properties:
      name:
        type: string
      path:
        type: string
      isDirectory:
        type: boolean
      size:
        type: string
        format: int64
      mimeType:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      content:
        type: string
        format: byte
        title: File content will be empty for now
      children:
        type: array
        items:
          type: object
          $ref: '#/definitions/chorusWorkspaceFile'
  chorusWorkspaceFilter:
    type: object
    properties:
      workspaceIdsIn:
        type: array
        items:
          type: string
          format: uint64
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
