ingress:
  enabled: true
  host: "backend.dev.chorus-tre.ch"
  loadBalancerIP: 86.119.30.38

service:
  port: 5000

deployment:
  postgresEnabled: false
  serviceAccountName: "backend-service-account"