apiVersion: v1
kind: Secret
metadata:
  name: backend-config-{{ include "chart.nameid" . }}
  labels:
    nameid: {{ include "chart.nameid" . }}
    version: {{ .Values.version }}
type: Opaque
data:
  config.yaml: {{ include "chart.main" . | b64enc }}