apiVersion: v1
kind: Secret
metadata:
  name: backend-config-{{ include "backend.nameid" . }}
  labels:
    nameid: {{ include "backend.nameid" . }}
    version: {{ .Values.version }}
type: Opaque
data:
  config.yaml: {{ include "backend.main" . | b64enc }}
  privkey.pem: "{{ (or (.Values.chorus_privkey).pem (.Files.Get "files/keys/chorus_privkey.pem") ) | b64enc }}"
  pubkey.pem: "{{ (or (.Values.chorus_pubkey).pem (.Files.Get "files/keys/chorus_pubkey.pem") ) | b64enc }}"
  