apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: backend-service-account  
  # namespace: backend 
roleRef:
  kind: ClusterRole
  name: backend-cluster-role
  apiGroup: rbac.authorization.k8s.io