apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-cluster-rolebinding-{{ include "backend.nameid" . }}
subjects:
- kind: ServiceAccount
  name: backend-service-account-{{ include "backend.nameid" . }}
  # namespace: backend 
roleRef:
  kind: ClusterRole
  name: backend-cluster-role-{{ include "backend.nameid" . }}
  apiGroup: rbac.authorization.k8s.io