apiVersion: v1
kind: Secret
metadata:
  name: backend-service-account-secret-{{ include "backend.nameid" . }}
  namespace: backend  
  annotations:
    kubernetes.io/service-account.name: backend-service-account-{{ include "backend.nameid" . }}
type: kubernetes.io/service-account-token