service-account-.yamlapiVersion: v1
kind: Secret
metadata:
  name: backend-service-account-secret
  namespace: backend  
  annotations:
    kubernetes.io/service-account.name: backend-service-account
type: kubernetes.io/service-account-token
