swagger: "2.0"
info:
  title: chorus steward service
  version: "1.0"
  contact:
    name: chorus steward service
    url: https://github.com/CHORUS-TRE/chorus-backend
    email: dev@chorus-tre.ch
tags:
  - name: StewardService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/rest/v1/steward/tenants/initialize:
    post:
      summary: Initialize a tenant
      description: This endpoint initializes a new tenant
      operationId: StewardService_InitializeTenant
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/chorusInitializeTenantRequest'
      tags:
        - StewardService
definitions:
  chorusInitializeTenantRequest:
    type: object
    properties:
      tenantId:
        type: string
        format: uint64
