CREATE DATABASE chorus_ci;
GRANT ALL PRIVILEGES ON DATABASE chorus_ci TO admin;

CREATE DATABASE audit;
CREATE USER audit WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE audit TO audit;

\c audit
GRANT ALL ON SCHEMA public TO audit;