// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.2
// source: terms-of-use.proto

package chorus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TermsOfUseVersionStatus int32

const (
	TermsOfUseVersionStatus_TERMS_OF_USE_VERSION_STATUS_DRAFT     TermsOfUseVersionStatus = 0
	TermsOfUseVersionStatus_TERMS_OF_USE_VERSION_STATUS_PUBLISHED TermsOfUseVersionStatus = 1
	TermsOfUseVersionStatus_TERMS_OF_USE_VERSION_STATUS_ARCHIVED  TermsOfUseVersionStatus = 2
)

// Enum value maps for TermsOfUseVersionStatus.
var (
	TermsOfUseVersionStatus_name = map[int32]string{
		0: "TERMS_OF_USE_VERSION_STATUS_DRAFT",
		1: "TERMS_OF_USE_VERSION_STATUS_PUBLISHED",
		2: "TERMS_OF_USE_VERSION_STATUS_ARCHIVED",
	}
	TermsOfUseVersionStatus_value = map[string]int32{
		"TERMS_OF_USE_VERSION_STATUS_DRAFT":     0,
		"TERMS_OF_USE_VERSION_STATUS_PUBLISHED": 1,
		"TERMS_OF_USE_VERSION_STATUS_ARCHIVED":  2,
	}
)

func (x TermsOfUseVersionStatus) Enum() *TermsOfUseVersionStatus {
	p := new(TermsOfUseVersionStatus)
	*p = x
	return p
}

func (x TermsOfUseVersionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TermsOfUseVersionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_terms_of_use_proto_enumTypes[0].Descriptor()
}

func (TermsOfUseVersionStatus) Type() protoreflect.EnumType {
	return &file_terms_of_use_proto_enumTypes[0]
}

func (x TermsOfUseVersionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TermsOfUseVersionStatus.Descriptor instead.
func (TermsOfUseVersionStatus) EnumDescriptor() ([]byte, []int) {
	return file_terms_of_use_proto_rawDescGZIP(), []int{0}
}

type TermsOfUseVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId  uint64                  `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Content   string                  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status    TermsOfUseVersionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=chorus.TermsOfUseVersionStatus" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *TermsOfUseVersion) Reset() {
	*x = TermsOfUseVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terms_of_use_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermsOfUseVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsOfUseVersion) ProtoMessage() {}

func (x *TermsOfUseVersion) ProtoReflect() protoreflect.Message {
	mi := &file_terms_of_use_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsOfUseVersion.ProtoReflect.Descriptor instead.
func (*TermsOfUseVersion) Descriptor() ([]byte, []int) {
	return file_terms_of_use_proto_rawDescGZIP(), []int{0}
}

func (x *TermsOfUseVersion) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TermsOfUseVersion) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TermsOfUseVersion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TermsOfUseVersion) GetStatus() TermsOfUseVersionStatus {
	if x != nil {
		return x.Status
	}
	return TermsOfUseVersionStatus_TERMS_OF_USE_VERSION_STATUS_DRAFT
}

func (x *TermsOfUseVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TermsOfUseVersion) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TermsOfUseAcceptance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId            uint64                 `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	UserId              uint64                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TermsOfUseVersionId uint64                 `protobuf:"varint,4,opt,name=termsOfUseVersionId,proto3" json:"termsOfUseVersionId,omitempty"`
	AcceptedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=acceptedAt,proto3" json:"acceptedAt,omitempty"`
}

func (x *TermsOfUseAcceptance) Reset() {
	*x = TermsOfUseAcceptance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terms_of_use_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermsOfUseAcceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsOfUseAcceptance) ProtoMessage() {}

func (x *TermsOfUseAcceptance) ProtoReflect() protoreflect.Message {
	mi := &file_terms_of_use_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsOfUseAcceptance.ProtoReflect.Descriptor instead.
func (*TermsOfUseAcceptance) Descriptor() ([]byte, []int) {
	return file_terms_of_use_proto_rawDescGZIP(), []int{1}
}

func (x *TermsOfUseAcceptance) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TermsOfUseAcceptance) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TermsOfUseAcceptance) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TermsOfUseAcceptance) GetTermsOfUseVersionId() uint64 {
	if x != nil {
		return x.TermsOfUseVersionId
	}
	return 0
}

func (x *TermsOfUseAcceptance) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

type TermsOfUseUserStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *TermsOfUseUserStatus) Reset() {
	*x = TermsOfUseUserStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terms_of_use_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermsOfUseUserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsOfUseUserStatus) ProtoMessage() {}

func (x *TermsOfUseUserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_terms_of_use_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsOfUseUserStatus.ProtoReflect.Descriptor instead.
func (*TermsOfUseUserStatus) Descriptor() ([]byte, []int) {
	return file_terms_of_use_proto_rawDescGZIP(), []int{2}
}

func (x *TermsOfUseUserStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_terms_of_use_proto protoreflect.FileDescriptor

var file_terms_of_use_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x2d, 0x6f, 0x66, 0x2d, 0x75, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x02,
	0x0a, 0x11, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x63, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc8, 0x01, 0x0a, 0x14, 0x54, 0x65, 0x72, 0x6d, 0x73,
	0x4f, 0x66, 0x55, 0x73, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x4f, 0x66, 0x55, 0x73,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x13, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x32, 0x0a, 0x14, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x2a, 0x95, 0x01, 0x0a, 0x17, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x21, 0x54, 0x45, 0x52, 0x4d, 0x53, 0x5f, 0x4f, 0x46, 0x5f, 0x55, 0x53,
	0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x00, 0x12, 0x29, 0x0a, 0x25, 0x54, 0x45, 0x52, 0x4d,
	0x53, 0x5f, 0x4f, 0x46, 0x5f, 0x55, 0x53, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x28, 0x0a, 0x24, 0x54, 0x45, 0x52, 0x4d, 0x53, 0x5f, 0x4f, 0x46, 0x5f,
	0x55, 0x53, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x63, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_terms_of_use_proto_rawDescOnce sync.Once
	file_terms_of_use_proto_rawDescData = file_terms_of_use_proto_rawDesc
)

func file_terms_of_use_proto_rawDescGZIP() []byte {
	file_terms_of_use_proto_rawDescOnce.Do(func() {
		file_terms_of_use_proto_rawDescData = protoimpl.X.CompressGZIP(file_terms_of_use_proto_rawDescData)
	})
	return file_terms_of_use_proto_rawDescData
}

var file_terms_of_use_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_terms_of_use_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_terms_of_use_proto_goTypes = []interface{}{
	(TermsOfUseVersionStatus)(0),  // 0: chorus.TermsOfUseVersionStatus
	(*TermsOfUseVersion)(nil),     // 1: chorus.TermsOfUseVersion
	(*TermsOfUseAcceptance)(nil),  // 2: chorus.TermsOfUseAcceptance
	(*TermsOfUseUserStatus)(nil),  // 3: chorus.TermsOfUseUserStatus
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_terms_of_use_proto_depIdxs = []int32{
	0, // 0: chorus.TermsOfUseVersion.status:type_name -> chorus.TermsOfUseVersionStatus
	4, // 1: chorus.TermsOfUseVersion.createdAt:type_name -> google.protobuf.Timestamp
	4, // 2: chorus.TermsOfUseVersion.updatedAt:type_name -> google.protobuf.Timestamp
	4, // 3: chorus.TermsOfUseAcceptance.acceptedAt:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_terms_of_use_proto_init() }
func file_terms_of_use_proto_init() {
	if File_terms_of_use_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_terms_of_use_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermsOfUseVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terms_of_use_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermsOfUseAcceptance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terms_of_use_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermsOfUseUserStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_terms_of_use_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terms_of_use_proto_goTypes,
		DependencyIndexes: file_terms_of_use_proto_depIdxs,
		EnumInfos:         file_terms_of_use_proto_enumTypes,
		MessageInfos:      file_terms_of_use_proto_msgTypes,
	}.Build()
	File_terms_of_use_proto = out.File
	file_terms_of_use_proto_rawDesc = nil
	file_terms_of_use_proto_goTypes = nil
	file_terms_of_use_proto_depIdxs = nil
}
