daemon:
  title: "template backend"
  http:
    host: 0.0.0.0
    port: 5000
    headers:
      access_control_allow_origins: 
      - "https://exodev.chorus-tre.ch"
      access_control_allow_origin_wildcard: false
      access_control_max_age: "600"
      cookie_domain: ".exodev.chorus-tre.ch"
  jwt:
    secret: "{{ .jwt_secret }}"
    expiration_time: 72h
    max_refresh_time: 4320h #180d
  jobs:
    job_status_gc:
      enabled: true
  private_key: "{{ .daemon_private_key }}"
  salt: feast-salutary3-online-slogan-chafe-july-rickety-desktop-from
  metrics:
    enabled: true
    authentication:
      enabled: true
      username: "{{ .metrics_username }}"
      password: "{{ .metrics_password }}"

storage:
  datastores:
    chorus:
      type: postgres
      migration_table_name: tt_migrations
      host: chorus-exodev-backend-db-postgresql
      port: 5432
      username: chorus-dev-user
      password: '{{ .postgres_password }}'
      database: chorus
      max_connections: 10
      max_lifetime: 10s
      debug_mode: true
      ssl:
        enabled: false
        certificate_file: /chorus/postgres-certs/client.crt
        key_file: /chorus/postgres-certs/client.key

services:
  index_service:
    key: value
  authentication_service:
    enabled: true
    dev_auth_enabled: true
    modes:
      internal:
        type: internal
        enabled: false
        public_registration_enabled: false
      keycloak:
        type: openid
        enabled: true
        main_source: true
        button_text: "Login with Keycloak"
        icon_url: "data:image/svg+xml;base64,CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1hcnJvdy1yaWdodCBtci0yIGgtNCB3LTQiPjxwYXRoIGQ9Ik01IDEyaDE0Ij48L3BhdGg+PHBhdGggZD0ibTEyIDUgNyA3LTcgNyI+PC9wYXRoPjwvc3ZnPgo="
        order: 1
        openid:
          id: keycloak
          chorus_backend_host: "https://backend.exodev.chorus-tre.ch"
          enable_frontend_redirect: true
          chorus_frontend_redirect_url: "https://exodev.chorus-tre.ch/oauthredirect"
          authorize_url: "https://auth.exodev.chorus-tre.ch/realms/chorus/protocol/openid-connect/auth"
          token_url: "https://auth.exodev.chorus-tre.ch/realms/chorus/protocol/openid-connect/token"
          user_info_url: "https://auth.exodev.chorus-tre.ch/realms/chorus/protocol/openid-connect/userinfo"
          logout_url: "https://auth.exodev.chorus-tre.ch/realms/chorus/protocol/openid-connect/logout?client_id=chorus&post_logout_redirect_uri=https://exodev.chorus-tre.ch"
          user_name_claim: "preferred_username"
          # final_url_format: "https://exodev.chorus-tre.ch/login?token=%s"
          client_id: chorus
          client_secret: "<secret>"
          scopes:
            - openid
            - profile
            - email
            - roles
  steward:
    init_tenant:
      enabled: true
    init_user:
      enabled: true
      username: chorus
      password: "{{ .steward_user_password }}"
      roles:
        - name: Authenticated
          context:
            user: 1
    init_workspace:
      enabled: true
      name: "Home workspace"
  mailer_service:
    smtp:
      user: smtpUser
      password: "<smtpPassword>"
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: "none"
  workbench_service:
    stream_proxy_enabled: true
    backend_in_k8s: true
    proxy_hit_save_batch_interval: 30s
    workbench_idle_timeout: 504h #21d

clients:
  docker_client:
    enabled: true
  k8s_client:
    enabled: true
    sa_secret_path: "/var/run/secrets/kubernetes.io/serviceaccount"
    api_server: "{{ .service_account_api_server_url }}"
    add_user_details: true

log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug