apiVersion: default.chorus-tre.ch/v1alpha1
kind: Workbench
metadata:
  name: {{ .Values.name }}
spec:
  imagePullSecrets:
    - "image-pull-secret"
    - regcred
  apps:
    {{- range .Values.apps }}
    - name: {{ .name }}
      image: {{ .image }}
      version: {{ .version }}
      {{- if .shmSize }}
      shmSize: {{ .shmSize }}
      {{- end }}
    {{- end }}
