daemon:
  title: "chorus"
  http:
    host: localhost
    port: 5000
    headers:
      access_control_allow_origin: "*"
      access_control_max_age: "600"
  jwt:
    secret: eREH6oV#&6bX&zadL%
    expiration_time: 259200 # 72h
  jobs:
    job_status_gc:
      enabled: true
  private_key_file: ./configs/dev/files/keys/chorus_privkey.pem
  public_key_file: ./configs/dev/files/keys/chorus_pubkey.pem
  salt: primary-2tiptop-violator-6bloating-2coastline-1spearmint-unruffled5-comfy-operation4

storage:
  datastores:
    chorus:
      type: postgres 
      host: 127.0.0.1
      port: 5432
      username: admin
      password: password
      database: chorus
      max_connections: 10
      max_lifetime: 10s
      ssl:
        enabled: false
        certificate_file: /chorus/postgres-certs/client.crt
        key_file: /chorus/postgres-certs/client.key

services:
  index_service:
    key: value
  authentication_service:
    enabled: true
  mailer_service:
    smtp:
      user: smtpUser
      password: smtpPassword
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: "none"

clients:
  helm_client:
    kube_config: |
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYkxJanhtNDAwWUl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1EY3hNalV5TURSYUZ3MHpOREE0TURVeE1qVTNNRFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR1dE9yT1dFNVQ5M2ZtZVdpWTM4eStPMEl6QWNmOHZvQ1QyQ2hidXovanNvQmE2L25tdzBlOWR2akwKZXZZVWJENHFHQU9IMk8vK0R6TVFhb1VtR0RVMU9wejQ3UCttbFE3Mmd1Z3pvU1RYL04raHZ2dlBLN0ZjdU9SQgp3Z0lHUEhnMjRjcU9vYk1iNmJBZVA0d2lBR1Fyb2xmNVdpMUNCOXEyaFRVUS9mbGxqU2lNbUVDSExQNDlmVUZGCnFoRWM5UEU4WXR1NkFLWVhGYjlNMGo0UXhXWUkzOGFXL1ZJSGthc3g4ZzluQzBtaUNzUjhBU2pVMHpleFNwT1IKMXY5bEdKQmRLZmZiRFJjNnU2c2tCcWtWQ0ZkVzVTT3FvS3Q4UFYxemlBWDBCS0g0QlVEY3Y4THF2NVhUODRSOApuVlF3T2VBUFN1d1hHYkQwb3BoL2dvK2tMUUVwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYjJHU3NhRy9EZzRGWCs0QW5Yb2tYNnhBWWp6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkJ1cmh0ZzJrbQpGNDdHUTBKdlU4UW0zZnJqN2FWTnplMHJZczhkK1daa1pMRTRqbDY0QkUvdEpFUlJJY0NXdlFIL2lyWUkvSVZ2CjhjYVVnenRQV0xEcGQ0cGRYUDdJazAyTWkrbWhXRktxNE9QYW9Od05MQk15T052amRuZHNua09wck9EeldtdFIKVlpxUUxENkVWeFJCR0JmN0lMZnFMdnRnSWZ1N0Z0Um9VK3lhSVJ3VmQ2UmVjdlZYQmpRRzVnN0ZTQnIzNHFRTAo3cHBZVm40RG50N0F5ejBlMnB5aFZUc3FkTFB0b1JBb1B2ZmljRkNUcjBJL2VzMzMwZWZVcVRYYU8xRTkxT3N1CkVtUHlnNjVxRmR1bDg4S0NqdXdWL2Y2encwK0hyZzU5eFphV2lRdkI0VnlGZmY5UDNWOHJaTDQvS3pPVXpoOEEKMm5zN0dmb3VsS2Z0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: https://127.0.0.1:38417
        name: kind-chorus
      contexts:
      - context:
          cluster: kind-chorus
          user: kind-chorus
        name: kind-chorus
      current-context: kind-chorus
      kind: Config
      preferences: {}
      users:
      - name: kind-chorus
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJZGt3WStDNXNVdmt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1EY3hNalV5TURSYUZ3MHlOVEE0TURjeE1qVTNNRFZhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDcC9uMk8KSTFCRVV1V3lic2xHNHF3c0ZHMXR1bkI5TkMza0gxNVZOMzRIQTdEUkRWOXVSV0lFektSbURaeUkydjNRV0xTRgpSS3ZKVE9tUit4Wi9va0dJeGJjcDhXdmJBUFlzU2dKbXZ2ZWFQQmlkMkt5a2RxbHFsQ1RaZmhGQ0s0WlFrSnJvCkRMSkJCUWs2dUtkRzNCQVRVdmNMa1lnTWpUbWRVMGZ1cE1UZDQ1V3ZVeHdvVGdZMGQ2RUdGRHJNcWNza2d3UVQKNkEwQWVDRFp0UUdiNks5WmNsODh4RFVPYzZ0WlR3dnBVdjR0ZEhhMTMyU3NtU2llZVFXa2JQUzBiM0QvbW5Edwo1bTI4MDQvM01QM211dEZ3WkZHdEJ4VDJUVWRNR2sybW5GcE1FeXFjamJRRFY3L0ZVWHd5NXA5Mnd1WXRjWlgwCkhUbjdVSjhUdE1mRTdaSFRBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkp2WVpLeG9iOE9EZ1ZmNwpnQ2RlaVJmckVCaVBNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUI4MGdhYzM2ZzdQU0hSNTZnbDc3R1dlTWFVCkg4RXlWUzdqYXd5aHl1UGlyd2N2K2ZUM1RzV2VNZ0VyWjVXcEVpUjRpTHkyNG84b2hvdlRWdTd1bG9EMVE3VFYKZGJpN0dzS1pMRytqSEI5L2MzbmZ6MkZWUXhkTFBpQUhZeHN4NzNMYWM2MmM0c1phdXBGY052cVFOd2lIemdzYwpMRnBweURKaXk2ZTFJckdtSGlhWjc0QXRsa0NCRmluWEFaODNyV1ppTitoUHNYZEpYY0V1YS9OcVdXSXFBS2I3ClhpSFQ3NWNLWDRjaXpTS1RBSTZ0YjVLZUJmSVlFNXpTZUhFU2oxV3phWnZlbnJxTDFvVHFaQkNDYXluSGdKQVcKYTY5bWpKNzZHRDlOOHp5dzBsMHh4VFVNN3dEM3ZQT210QktuN2Ruc3FxZmd1OGZpQklYcHI3K3EzWGZRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBcWY1OWppTlFSRkxsc203SlJ1S3NMQlJ0YmJwd2ZUUXQ1QjllVlRkK0J3T3cwUTFmCmJrVmlCTXlrWmcyY2lOcjkwRmkwaFVTcnlVenBrZnNXZjZKQmlNVzNLZkZyMndEMkxFb0NacjczbWp3WW5kaXMKcEhhcGFwUWsyWDRSUWl1R1VKQ2E2QXl5UVFVSk9yaW5SdHdRRTFMM0M1R0lESTA1blZOSDdxVEUzZU9WcjFNYwpLRTRHTkhlaEJoUTZ6S25MSklNRUUrZ05BSGdnMmJVQm0raXZXWEpmUE1RMURuT3JXVThMNlZMK0xYUjJ0ZDlrCnJKa29ubmtGcEd6MHRHOXcvNXB3OE9adHZOT1A5ekQ5NXJyUmNHUlJyUWNVOWsxSFRCcE5wcHhhVEJNcW5JMjAKQTFlL3hWRjhNdWFmZHNMbUxYR1Y5QjA1KzFDZkU3VEh4TzJSMHdJREFRQUJBb0lCQVFDaDMyb2puVkRqbnFTSApZcU5iVXFGc1lBOUx1NHMrVGgrYzZKbmxQN0JNY2FFL2tDSmRXTWhibFpxK2F4dXgzZ1p2RE9qcE5sajJtTHlaCmU2VVM2S2pLMnFydHo2eEtvUUhKYnJnV3FxWVFRa1dXbVNyY2VQb2VPTzlXQTR2Zm5KNkx2UWNsREdINU5CaHoKeUQzUlplQVE1cUhFYkZKRzBYd1phYUpIaHJMSUxrOTZERFFRRWlNSzRJQmpHcmZJSUk3MndSNlJJLzJ3UjFSYQpJcEF1Uzl6WDFXR1E4WERQT2VoOElnaERZNWR5akVGdVBJUGFwSmhyS0pDWVhmMXRyNk9yTTJFQ0ExeWlxYm1jCmlLVlVyclp3TW1tVUt2a0RYVThGeWR2K3hFQkw2cVVlNUNLL0RyTmtGdVBjSC8wNHFzdm9mK0tyV0JrcDltK3kKaERuNjQweFJBb0dCQU5aOUMxNHdzWGZTbjdkQ0hvREllSCs2d2NOcnpodW5GTmlGSE1zTDhkWUZxN0pITWR1OQo5cmhOOHRuMURNWFZ4NElvUUpWcktGbzhaOTBscktEbXFEL0ZyV2ZESmI1Y0dKQVRwOGtVTkJwTlFaeG5kWHhsCnlKdXdiUlJvR0JodVZaMGFwTlRUbmdCR0xJblNYWmJEdGhha2gxZDFMT0ZkektDNHlTOVMwanhuQW9HQkFNcmsKOG93NUk0ZUhCT2FLODVzMG8wWGkzZlJCdThjMTZIZ2RYZzg2SzlvOU9za3dacDdxMHo1cTMzaWN3bHRFalhGSQpJVHZOY0Fud2UydjY3Z1NtVWEwTkNTS0dRRm1pV3dIMnBJOW1xZUgrTkZER1FHU01NWGZ5OTVyandsd2FXOExRCkhkRGZoOG83bnhmYnlpbW5UejgvZksyM2orSzZGYklpQ0I2MGhodTFBb0dCQUlIejB4NW5UQzczK3ZMU2FaN0gKVjFLME9VK0lrcURvYzFYWUdLRGhCTTRTTTN2WmJOamhXSWxFR1A1N1hSakVOSk9raGJUQjd2bjFIVXk4MWNISwozbWQ5QWxvYXYxUjlnaGhSQUZoeEdEeFRVSXhObHI0ZkFSTnJLanV4OGQ5amdoV2tuZmVnbTFzNUtTVDd3dDVrCmgzOWlnZW00UWMvdHY5d2srU2ZsK3lEREFvR0JBSlVJUk8waEQycitqMmYwaXVubmFVTHRXTkdROHlocC9aODEKR3lFZVBwWG93ZVNFUyt6UldtZVB3eVJxS1EwM05wb09QSE1iL1A4Z0NOaVJFZ0tTVkk1RGRBRkxFYnVGV1VvQQo3SEYxSExZbXJqRGkzdXU4V3AzYjkycHJnQmw5TndmTExRdC9GZFJEcFNHMlRUSDVkbWxqN2VZQVhvMVEySnpuCkNJWGRYbUM5QW9HQWI2c3hWRFdGdkVXS2pXQXRESFQvWk1rTWZxQWZnR1I2Y1BvRzIrTndyamlLNC81dFJhYi8KT3FpUHZtbGRTT3FuZXBpbVp3dkJQTjZQaXNOUDkzclNoTWZhWHEzN3hKcVJSUzZBbE54V3FJc1RMU1FEOXl6agpSKzNBY1hEMndmOThidlRmSGVwa0FLSndkUFQ0MXhENUMxQ1BNNGVCSmhLaCtqSmpDcjgwMDFVPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug

