services:
  authentication_service:
    modes:
      keycloak:
        openid:
          client_secret: ""
      keycloakdev:
        openid:
          client_secret: ""

clients:
  harbor_client:
    password: ""
  k8s_client:
    api_server: https://127.0.0.1:<port> # from generated kubeconfig
    ca: | # from generated kubeconfig
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    token: "" # chorus-admin service account token
    image_pull_secrets:
      - registry: ""
        username: ""
        password: ""
