daemon:
  title: "template backend"
  http:
    host: localhost
    port: 5000
    headers:
      access_control_allow_origin: "*"
      access_control_max_age: "600"
  jwt:
    secret: eREH6oV#&6bX&zadL%
    expiration_time: 259200 # 72h
  jobs:
    job_status_gc:
      enabled: true
  private_key_file: ./configs/dev/files/keys/template_backend_privkey.pem
  public_key_file: ./configs/dev/files/keys/template_backend_pubkey.pem

storage:
  datastores:
    template_backend:
      type: postgres
      driver: psycopg2
      migration_table_name: tt_migrations
      host: postgres
      port: 5432
      username: admin
      password: password
      database: template_backend
      max_connections: 10
      max_lifetime: 10s
      debug_mode: true
      ssl:
        enabled: false
        certificate_file: /template_backend/postgres-certs/client.crt
        key_file: /template_backend/postgres-certs/client.key

services:
  index_service:
    key: value
  authentication_service:
    enabled: true
  mailer:
    smtp:
      user: smtpUser
      password: smtpPassword
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: plain

log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug

