swagger: "2.0"
info:
  title: CHORUS backend API
  description: CHORUS backend API documentation
  version: "1.0"
  contact:
    name: CHORUS dev team
    url: https://www.chorus-tre.ch
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
securityDefinitions:
  bearer:
    type: apiKey
    description: 'Authentication token: Bearer <token>'
    name: Authorization
    in: header
security:
  - bearer: []
