image:
  repository: harbor.int.chorus-tre.ch/backend-master/backend
  imagePullPolicy: Always

service:
  port: 5000

# Disable mounting of secrets volume and config override
# all password will need to be set via the config below
# which is not recommended for production use cases
disableMountSecrets: false
config:
  clients:
    harbor_client:
      url: "https://harbor.int.chorus-tre.ch"
      username: "robot$chorus-int"
      password: "" # set in secret
    k8s_client:
      default_registry: "https://harbor.int.chorus-tre.ch"
  daemon:
    jwt:
      secret: "" # set in secret
    private_key: "" # set in secret
    salt: feast-salutary3-online-slogan-chafe-july-rickety-desktop-from
    http:
      headers:
        access_control_allow_origins:
          - "https://int.chorus-tre.ch"
          - "https://backend.int.chorus-tre.ch"
          - "http://localhost:3000"
        cookie_domain: ".int.chorus-tre.ch"
    expose_error_stack_trace: true
    metrics:
      authentication:
        enabled: true
        password: "" # set in secret
  services:
    authentication_service:
      modes:
        internal:
          main_source: false
          public_registration_enabled: false
        keycloak:
          enabled: true
          main_source: true
          openid:
            chorus_backend_host: "https://backend.int.chorus-tre.ch"
            chorus_frontend_redirect_url: "https://int.chorus-tre.ch/oauthredirect"
            authorize_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/auth"
            token_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/token"
            user_info_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/userinfo"
            logout_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/logout?client_id=chorus&post_logout_redirect_uri=https://int.chorus-tre.ch"
            client_secret: "" # set in secret
        keycloakdev:
          type: openid
          enabled: true
          button_text: "Login with Keycloak - dev mode"
          order: 3
          openid:
            id: keycloakdev
            chorus_backend_host: "https://backend.int.chorus-tre.ch"
            enable_frontend_redirect: true
            chorus_frontend_redirect_url: "http://localhost:3000/oauthredirect"
            authorize_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/auth"
            token_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/token"
            user_info_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/userinfo"
            logout_url: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/logout?client_id=chorus&post_logout_redirect_uri=http://localhost:3000"
            user_name_claim: "preferred_username"
            client_id: chorus
            client_secret: ""  # set in secret
            scopes:
              - openid
              - profile
              - email
              - roles
    workbench_service:
      backend_in_k8s: true
      workbench_idle_timeout: 504h #21d
    workspace_file_service:
      stores:
        archive:
          workspace_prefix: "workspaces/%s/data" # where %s will be replaced by the namespace name (workspace+id)
    approval_request_service:
      staging_file_store_name: archive
    openid_connect_provider:
      enabled: true
      issuer_url: "https://backend.int.chorus-tre.ch/openid-connect"
      frontend_interactions_url: "https://backend.int.chorus-tre.ch/auth-ui"
      jwks: "" # set in secret
      clients: [] # set in secret
    steward:
      user:
        password: "" # set in secret
  storage:
    datastores:
      audit:
        host: chorus-int-audit-db-postgresql
        username: backend-audit
        password: "" # set in secret
      chorus:
        host: chorus-int-backend-db-postgresql
        username: backend
        password: "" # set in secret
    file_stores:
      archive:
        minio_config:
          endpoint: juicefs-s3-gateway.kube-system.svc.cluster.local:9000
          access_key_id: "" # set in secret
          secret_access_key: "" # set in secret
      disk:
        disk_config:
          enabled: false
