image:
  repository: harbor.int.chorus-tre.ch/backend-master/backend
  imagePullPolicy: Always

service:
  port: 5000

serviceMonitor:
  enabled: true
  basicAuth:
    enabled: true
    secretName: "chorus-int-backend-metrics"

# Disable mounting of secrets volume and config override
# all password will need to be set via the config below
# which is not recommended for production use cases
disableMountSecrets: false
config:
  clients:
    harbor:
      url: "https://harbor.int.chorus-tre.ch"
      username: "robot$chorus-int"
      password: "" # set in secret
    kubernetes:
      defaultRegistry: "https://harbor.int.chorus-tre.ch"
  daemon:
    jwt:
      secret: "" # set in secret
    privateKey: "" # set in secret
    salt: feast-salutary3-online-slogan-chafe-july-rickety-desktop-from
    http:
      headers:
        accessControlAllowOrigins:
          - "https://int.chorus-tre.ch"
          - "https://backend.int.chorus-tre.ch"
          - "http://localhost:3000"
        cookieDomain: ".int.chorus-tre.ch"
    exposeErrorStackTrace: true
    metrics:
      authentication:
        enabled: true
        password: "" # set in secret
  services:
    authenticationService:
      modes:
        internal:
          mainSource: false
          publicRegistrationEnabled: false
        keycloak:
          enabled: true
          mainSource: true
          openid:
            chorusBackendHost: "https://backend.int.chorus-tre.ch"
            chorusFrontendRedirectUrl: "https://int.chorus-tre.ch/oauthredirect"
            authorizeUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/auth"
            tokenUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/token"
            userInfoUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/userinfo"
            logoutUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/logout?client_id=chorus&post_logout_redirect_uri=https://int.chorus-tre.ch"
            clientSecret: "" # set in secret
        keycloakdev:
          type: openid
          enabled: true
          buttonText: "Login with Keycloak - dev mode"
          order: 3
          openid:
            id: keycloakdev
            chorusBackendHost: "https://backend.int.chorus-tre.ch"
            enableFrontendRedirect: true
            chorusFrontendRedirectUrl: "http://localhost:3000/oauthredirect"
            authorizeUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/auth"
            tokenUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/token"
            userInfoUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/userinfo"
            logoutUrl: "https://auth.int.chorus-tre.ch/realms/chorus/protocol/openid-connect/logout?client_id=chorus&post_logout_redirect_uri=http://localhost:3000"
            userNameClaim: "preferred_username"
            clientId: chorus
            clientSecret: ""  # set in secret
            scopes:
              - openid
              - profile
              - email
              - roles
    workbenchService:
      backendInK8s: true
      workbenchIdleTimeout: 504h #21d
    workspaceFileService:
      stores:
        archive:
          workspacePrefix: "workspaces/%s/data" # where %s will be replaced by the namespace name (workspace+id)
    approvalRequestService:
      stagingFileStoreName: archive
    openidConnectProvider:
      enabled: true
      issuerUrl: "https://backend.int.chorus-tre.ch/openid-connect"
      frontendInteractionsUrl: "https://backend.int.chorus-tre.ch/auth-ui"
      jwks: "" # set in secret
      clients: [] # set in secret
    steward:
      user:
        password: "" # set in secret
  storage:
    datastores:
      audit:
        host: chorus-int-audit-db-postgresql
        username: backend-audit
        password: "" # set in secret
      chorus:
        host: chorus-int-backend-db-postgresql
        username: backend
        password: "" # set in secret
    fileStores:
      archive:
        minioConfig:
          endpoint: juicefs-s3-gateway.kube-system.svc.cluster.local:9000
          accessKeyId: "" # set in secret
          secretAccessKey: "" # set in secret
      disk:
        diskConfig:
          enabled: false
