daemon:
  title: "template backend"
  http:
    host: localhost
    port: 5000
    headers:
      access_control_allow_origins: 
        - "localhost"
      access_control_allow_origin_wildcard: true
      access_control_max_age: "600"
      cookie_domain: "localhost"
  jwt:
    secret: "{{ .jwt_secret }}"
    expiration_time: 72h
    max_refresh_time: 4320h #180d
  jobs:
    job_status_gc:
      enabled: true
  private_key_file: ./configs/dev/files/keys/chorus_privkey.pem
  public_key_file: ./configs/dev/files/keys/chorus_pubkey.pem
  salt: supreme-stung-pointy-demise3-blizzard-briskness-scrawny-shush-exalted

storage:
  datastores:
    chorus:
      type: postgres
      migration_table_name: tt_migrations
      host: localhost
      port: 5432
      username: admin
      password: password
      database: chorus
      max_connections: 10
      max_lifetime: 10s
      debug_mode: true
      ssl:
        enabled: false
        certificate_file: /chorus/postgres-certs/client.crt
        key_file: /chorus/postgres-certs/client.key

services:
  index_service:
    key: value
  authentication_service:
    enabled: true
  mailer:
    smtp:
      user: smtpUser
      password: smtpPassword
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: plain

log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug

