apiVersion: v1
kind: Pod
metadata:
  name: unit
spec:
  containers:
  - name: chorus-ubuntu
    image: registry.dip-dev.thehip.app/chorus-stage1
    imagePullPolicy: Always
    tty: true
    volumeMounts:
    - name: go-build-cache
      mountPath: /chorus/.cache/go-build
    - name: go-mod-cache
      mountPath: /chorus/.cache/go-mod
    - name: docker
      mountPath: /run/docker.sock
    - name: docker-config
      mountPath: /chorus/chorus-deployer/.docker/secret
    env:
      - name: CONFIG_AES_PASSPHRASE_ci
        valueFrom:
          secretKeyRef:
            name: configaespassphrase-ci
            key: passphrase
      - name: CONFIG_AES_PASSPHRASE_int
        valueFrom:
          secretKeyRef:
            name: configaespassphrase-int
            key: passphrase
    lifecycle:
      postStart:
        exec:
          command: ['sh', '-c', "cp /chorus/chorus-deployer/.docker/secret/config.json /chorus/chorus-deployer/.docker/config.json"]
  - name: jnlp
    image: registry.dip-dev.thehip.app/chorus-jnlp/jenkins/inbound-agent:3107.v665000b_51092-15
    imagePullPolicy: Always
  imagePullSecrets:
  - name: registry-auth
  volumes:
  - name: go-build-cache
    hostPath:
      path: /home/dipadmin/.cache/go-build
  - name: go-mod-cache
    hostPath:
      path: /home/dipadmin/.cache/go-mod
  - name: docker
    hostPath:
      path: /run/docker.sock
  - name: docker-config
    secret:
      secretName: registry-auth
      items:
      - key: .dockerconfigjson
        path: config.json
