{{- $secret := lookup "v1" "Secret" .Release.Namespace "regred" -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson | b64enc | quote }}
{{- end }}