apiVersion: default.chorus-tre.ch/v1alpha1
kind: Workbench
metadata:
  name: {{ .Values.name }}
spec:
  imagePullSecrets: 
    - "image-pull-secret"
  {{- if .Values.server }}
  server:
    version: {{ .Values.server.version }}
  {{- end }}
  apps:
    {{- if .Values.apps }}
    {{- range .Values.apps }}
    - name: {{ .name }}
      image: 
        registry: {{ .image.registry }}
        repository: {{ .image.repository }}
        tag: {{ .image.tag }}
      version: {{ .version }}
      {{- if .shmSize }}
      shmSize: {{ .shmSize }}
      {{- end }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
