daemon:
  http:
    host: localhost
    port: 5000
    headerClientIp: True-Client-IP
  grpc:
    host: 127.0.0.1
    port: 5555
  jwt:
    secret: jwt_secret
    expirationTime: 10s
  totp:
    numRecoveryCodes: 10
  exposeErrorStackTrace: true
  salt: 1234

storage:
  datastores:
    chorus:
      type: postgres
      host: localhost
      port: 40657
      username: root
      password: password
      database: chorus
      maxConnections: 10
      maxLifetime: 10s
      ssl:
        enabled: true
        certificateFile: /chorus/postgres-certs/client.crt
        keyFile: /chorus/postgres-certs/client.key
    audit:
      type: postgres
      host: localhost
      port: 4567
      username: audit_user
      password: password
      database: audit
      maxConnections: 10
      maxLifetime: 10s
      ssl:
        enabled: false
log:
  loggers:
    stdout_technical:
      enabled: true
      type: stdout
      level: info
      category: technical
    stdout_business:
      enabled: true
      type: stdout
      level: info
      category: business
    stdout_security:
      enabled: true
      type: stdout
      level: warn
      category: security
    file_technical:
      enabled: true
      type: file
      level: error
      category: technical
      path: /var/log/chorus/technical.log
      maxAge: 7
      maxBackups: 20
      maxSize: 50
    redis_technical:
      enabled: true
      type: redis
      level: info
      category: technical
      host: redis
      port: 6379
      database: 0
      password: redis_password
      key: log
    # For Graylog, only the "GELF HTTP" inputs are supported
    graylog_technical:
      type: graylog
      enabled: true
      level: debug
      category: technical
      graylogTimeout: 5s
      graylogHost: http://local.chorus-tre.ch:12201/gelf   # Must include the entire ingestor URL (typically at /gelf)
      graylogBulkReceiving: true                            # Must be aligned with the "Enable Bulk Receiving" option of the graylog Input
      graylogAuthorizeSelfSignedCertificate: true           # For TLS/HTTPS, skip certificate authority signature

services:
  auditService:
    enabled: true
    datastoreName: audit
  steward:
    tenant:
      name: default
    user:
      username: chorus
      password: "password"

tenants:
  88888:
    ipWhitelist:
      enabled: true
      subnetworks:
        - 127.0.0.1/32
        - 10.1.0.0/16


